const STATUS_OK = 200;

const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHORIZED = 401;

const STATUS_INTERNAL_SERVER_ERROR = 500;

export default {
    STATUS_OK,
    STATUS_BAD_REQUEST,
    STATUS_INTERNAL_SERVER_ERROR,
    STATUS_UNAUTHORIZED
}